name: Test
on:
  push:
  
jobs:
  Build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: build
          shell: bash
          run: |
            cmake -H. -B_build
            cmake --build _build
          
